version: '3.4'

services:
  carserviceapi:
    image: ${DOCKER_REGISTRY-}carserviceapi
    build:
      context: .
      dockerfile: CarServiceApi/Dockerfile

  webservice-db:
    image: postgres:latest
    environment:
        POSTGRES_DB: carservice-db
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: password
    volumes:
      - webservice-db-vol:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - "5432:5432"

volumes:
  webservice-db-vol:
